//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hai_1911060974.VuHai_1911060974 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VuHai_1911060974.IIServiceVu_Hai")]
    public interface IIServiceVu_Hai {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IIServiceVu_Hai/GetMessageWithoutAnyProtection", ReplyAction="http://tempuri.org/IIServiceVu_Hai/GetMessageWithoutAnyProtectionResponse")]
        string GetMessageWithoutAnyProtection(string messenger);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IIServiceVu_Hai/GetMessageWithoutAnyProtection", ReplyAction="http://tempuri.org/IIServiceVu_Hai/GetMessageWithoutAnyProtectionResponse")]
        System.Threading.Tasks.Task<string> GetMessageWithoutAnyProtectionAsync(string messenger);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/IIServiceVu_Hai/GetSignedMessage", ReplyAction="http://tempuri.org/IIServiceVu_Hai/GetSignedMessageResponse")]
        string GetSignedMessage();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://tempuri.org/IIServiceVu_Hai/GetSignedMessage", ReplyAction="http://tempuri.org/IIServiceVu_Hai/GetSignedMessageResponse")]
        System.Threading.Tasks.Task<string> GetSignedMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IIServiceVu_Hai/GetSignedAndEncrytedMessage", ReplyAction="http://tempuri.org/IIServiceVu_Hai/GetSignedAndEncrytedMessageResponse")]
        string GetSignedAndEncrytedMessage();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IIServiceVu_Hai/GetSignedAndEncrytedMessage", ReplyAction="http://tempuri.org/IIServiceVu_Hai/GetSignedAndEncrytedMessageResponse")]
        System.Threading.Tasks.Task<string> GetSignedAndEncrytedMessageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIServiceVu_HaiChannel : Hai_1911060974.VuHai_1911060974.IIServiceVu_Hai, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IServiceVu_HaiClient : System.ServiceModel.ClientBase<Hai_1911060974.VuHai_1911060974.IIServiceVu_Hai>, Hai_1911060974.VuHai_1911060974.IIServiceVu_Hai {
        
        public IServiceVu_HaiClient() {
        }
        
        public IServiceVu_HaiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IServiceVu_HaiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IServiceVu_HaiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IServiceVu_HaiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessageWithoutAnyProtection(string messenger) {
            return base.Channel.GetMessageWithoutAnyProtection(messenger);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageWithoutAnyProtectionAsync(string messenger) {
            return base.Channel.GetMessageWithoutAnyProtectionAsync(messenger);
        }
        
        public string GetSignedMessage() {
            return base.Channel.GetSignedMessage();
        }
        
        public System.Threading.Tasks.Task<string> GetSignedMessageAsync() {
            return base.Channel.GetSignedMessageAsync();
        }
        
        public string GetSignedAndEncrytedMessage() {
            return base.Channel.GetSignedAndEncrytedMessage();
        }
        
        public System.Threading.Tasks.Task<string> GetSignedAndEncrytedMessageAsync() {
            return base.Channel.GetSignedAndEncrytedMessageAsync();
        }
    }
}
